"""crear tablas inventario y movimientos_stock

Revision ID: 2c77f3a5fc80
Revises: ad55d91d9e5a
Create Date: 2026-08-24 02:50:41.525563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c77f3a5fc80'
down_revision = 'ad55d91d9e5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventario',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('sucursal_id', sa.UUID(), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id', 'sucursal_id', name='uq_inventario_producto_sucursal')
    )
    op.create_table('movimientos_stock',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('producto_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'salida', 'transferencia', name='tipo_movimiento_enum'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('sucursal_origen_id', sa.UUID(), nullable=True),
    sa.Column('sucursal_destino_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('motivo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['sucursal_destino_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['sucursal_origen_id'], ['sucursales.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimientos_stock')
    op.drop_table('inventario')
    # ### end Alembic commands ###
